# Generated by Django 4.2.6 on 2023-10-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_trend_search_period_trend_search_results_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trend',
            name='start_date',
        ),
    ]
