# Generated by Django 4.2.6 on 2023-10-13 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0003_remove_trend_end_date_remove_trend_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='keyword',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='trends.keyword'),
        ),
    ]
