# Generated by Django 4.2.6 on 2023-10-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_alter_trend_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trend',
            name='keyword',
        ),
    ]
