# Generated by Django 4.2.6 on 2023-10-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0006_remove_trend_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='keyword',
            field=models.CharField(default='기본값', max_length=100),
        ),
    ]
