# Generated by Django 4.2.6 on 2023-10-13 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0008_remove_trend_description_remove_trend_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 6, 49, 42, 701308, tzinfo=datetime.timezone.utc)),
        ),
    ]
