# Generated by Django 4.2.6 on 2023-10-13 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0009_trend_is_active_alter_trend_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 7, 48, 28, 54754, tzinfo=datetime.timezone.utc)),
        ),
    ]
