# Generated by Django 4.2.6 on 2023-10-13 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0011_alter_trend_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 8, 50, 30, 204601, tzinfo=datetime.timezone.utc)),
        ),
    ]
