# Generated by Django 4.2.6 on 2023-10-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0003_alter_depositoptions_intr_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
